=== dyshechka/lab2-xml/src/application.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT application (codeWord, loanProductId, tradePoint, incomeType, monthlyIncome, initialPayment, loanTerm, transferClaimAgree, draft, goods, person)>
        <!ATTLIST application number ID #REQUIRED>
            <!ELEMENT codeWord (#PCDATA)>
            <!ELEMENT loanProductId (#PCDATA)>
            <!ELEMENT tradePoint (#PCDATA)>
            <!ELEMENT incomeType (#PCDATA)>
            <!ELEMENT monthlyIncome (#PCDATA)>
            <!ELEMENT initialPayment (#PCDATA)>
            <!ELEMENT loanTerm (#PCDATA)>
            <!ELEMENT transferClaimAgree (#PCDATA)>
            <!ELEMENT draft (#PCDATA)>
                <!ATTLIST draft applicationId IDREF #REQUIRED>

            <!ELEMENT goods (good)+>
            <!ELEMENT good (name, quantity, cost)>
                <!ELEMENT name (#PCDATA)>
                <!ELEMENT quantity (#PCDATA)>
                <!ELEMENT cost (#PCDATA)>

            <!ELEMENT person (firstName, lastName, patronymic, gender, birthDate, birthPlace, contacts, documents)>
                <!ELEMENT firstName (#PCDATA)>
                <!ELEMENT lastName (#PCDATA)>
                <!ELEMENT patronymic (#PCDATA)>
                <!ELEMENT gender (#PCDATA)>
                <!ELEMENT birthDate (#PCDATA)>
                <!ELEMENT birthPlace (#PCDATA)>

                <!ELEMENT contacts (contact)+>
                <!ELEMENT contact (contactType, contactValue)>
                    <!ELEMENT contactType (#PCDATA)>
                    <!ELEMENT contactValue (#PCDATA)>

                <!ELEMENT documents (document)+>
                <!ELEMENT document (documentNumber, documentSerialNumber, documentType, issueDate, issuedBy, subdivisionCode)>
                    <!ELEMENT documentNumber (#PCDATA)>
                    <!ELEMENT documentSerialNumber (#PCDATA)>
                    <!ELEMENT documentType (#PCDATA)>
                    <!ELEMENT issueDate (#PCDATA)>
                    <!ELEMENT issuedBy (#PCDATA)>
                    <!ELEMENT subdivisionCode (#PCDATA)>

=== dyshechka/lab2-xml/src/applicationDTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE application SYSTEM "application.dtd">
<application number="ID1">
    <codeWord>КОДОВОЕ СЛОВО</codeWord>
    <loanProductId>ПРЕМИУМ 17%</loanProductId>
    <tradePoint>909205501</tradePoint>
    <incomeType>1</incomeType>
    <monthlyIncome>12000</monthlyIncome>
    <initialPayment>1300</initialPayment>
    <loanTerm>17</loanTerm>
    <transferClaimAgree>true</transferClaimAgree>
    <draft applicationId="ID1">1232456</draft>
    <goods>
        <good>
            <name>ХОЛОДИЛЬНИК</name>
            <quantity>1</quantity>
            <cost>20000</cost>
        </good>
    </goods>
    <person>
        <firstName>МАРТА</firstName>
        <lastName>ХАРИТОНОВА</lastName>
        <patronymic>ЛЕОНИДОВНА</patronymic>
        <gender>1</gender>
        <birthDate>1995-03-19</birthDate>
        <birthPlace>СЫКТЫВКАР</birthPlace>
        <contacts>
            <contact>
                <contactType>1</contactType>
                <contactValue>9876543210</contactValue>
            </contact>
            <contact>
                <contactType>2</contactType>
                <contactValue>1234567890</contactValue>
            </contact>
        </contacts>
        <documents>
            <document>
                <documentNumber>1714</documentNumber>
                <documentSerialNumber>123456</documentSerialNumber>
                <documentType>1</documentType>
                <issueDate>2017-01-01</issueDate>
                <issuedBy>МРО УФМС РОССИИ ПО ВЛАДИМИРСКОЙ ОБЛАСТИ</issuedBy>
                <subdivisionCode>330-040</subdivisionCode>
            </document>
        </documents>
    </person>
</application>
